### ISSUE TITLE
Nicolas Abril

### ISSUE THREAD

**Issue by developedby** [Kindelia/class-solutions#7]
git submodule add https://gitlab.com/nicolasabril/kind-class.git nicolas-abril

**Comment by gabriel-del** [comment]
@rafaelnsantos @developedby 
Por favor, vejam se vocês conseguem deixar linkável esse repositório do gitlab

**Comment by rafaelnsantos** [comment]
Aqui na página do github não mostra o link mas quando clona com ```--recursive``` funciona.

Acho que a única forma para resolver seria se o @developedby mudasse o repositório dele para o github.

**Comment by developedby** [comment]
Não entendi exatamente qual o problema, mas passei pro github como voce pediu
git submodule add https://github.com/developedby/class.git nicolas-abril

**Comment by gabriel-del** [comment]
Por esse repositório do github, não estava sendo possível acessar diretamente o seu no gitlab.
Obrigado.
